### ISSUE TITLE
Roadmap to `v0.1.0`

### ISSUE THREAD

**Issue by avhz** [avhz/RustQuant#187]
This is the roadmap for getting RustQuant to a solid `v0.1.0`.

High priority to-do list:

- [ ] Implement `Curve` type.
- [ ] Implement `Surface` type.
- [ ] Rework bond pricing module.
- [ ] Rework option pricing module.
- [ ] Implement `Payoff` trait for defining (custom) payoffs.
- [ ] Implement `Exercise` trait.
- [ ] Implement Swap Pricer. 

Low priority to-do list:

- [ ] Decrease the compile times (prune dependencies where possible, for example). 
- [ ] Implement a new `MultiFactorStochasticProcess` that can implement multi-factor models, such as Heston, SABR, Libor Market Model, Chen Model, etc. 

Notes:

- Make use of `#[derive(derive_builder::Builder)]` where it makes sense, such as for building financial instruments. This also has the benefit of providing default arguments.
